# changes made
version: "3.3"
services:
  baseball:
    container_name: baseball
    depends_on:
      - mariadb2
    build:
      context: .
      dockerfile: Dockerfile2
    volumes:
      - ./output:/output
    networks:
      - backend

  mariadb2:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb2
    restart: "no"
    volumes:
      - ./db:/config
    networks:
      - backend
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/London
    ports:
      - 3307:3307
networks:
  backend:
